
# This file is autogenerated by C:\Users\david\Documents\coding\override\override\tools.py

from example.my_configs.two import *

# runtime overrides
from override.tools import RuntimeUpdates as _RTU
_RTU('fizz').apply_all(locals())


print(42*'#')
print('# ', 'configuration: %s' % 'two')
print('# ', 'version: unknown')
print(42*'#')

